version: "3.9"
services:
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=myuser
      - POSTGRES_DB=postgres_db
    volumes:
      - ./storage/solardata:/var/lib/postgresql/data

  web:
    image: my-project-web-application
    depends_on:
      - db
    ports:
      - 8000:8000
    build: ./web
    volumes:
      - ./web:/web

  collector:
    depends_on:
      - db
    ports:
      - 5003:5003
    build: ./storage